# Generated by Django 4.2 on 2023-04-28 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='note',
            new_name='about',
        ),
    ]
